services:
  postgres:
    image: postgres:15-alpine
    container_name: my-nest-project-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Strong_New_Password_123!
      POSTGRES_DB: nest_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: